// app/layout.tsx
import { ReactNode } from 'react';

// SEO Configuration Metadata: Next.js reads this to inject tags into the HTML header automatically
export const metadata = {
    title: 'Next.js Learning Hub',
    description: 'Generated by Next.js',
};

interface RootLayoutProps {
    children: ReactNode; // Represents whatever page component Next.js is currently rendering
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            {/* The layout defines the global HTML shell. 
        The {children} expression injects your current route page (like app/page.tsx) 
        directly inside the body tags!
      */}
            <body>{children}</body>
        </html>
    );
}